import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import { FilterProvider } from "@/providers/FilterProvider";
import "./globals.css";
import Header from "@/components/Header/header";

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700'],
  variable: '--font-roboto-condensed',
});

export const metadata: Metadata = {
  title: "USC DAYS WEBSITE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <FilterProvider>
        <body
          className={`${robotoCondensed.variable}`}
        >
          <Header />
          {children}
        </body>
      </FilterProvider>
    </html>
  );
}
